// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: differential_test.proto

#include "differential_test.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_differential_5ftest_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Company_differential_5ftest_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_differential_5ftest_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_DependentInfo_differential_5ftest_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_differential_5ftest_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_EducationInfo_differential_5ftest_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_differential_5ftest_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ExamScore_differential_5ftest_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_differential_5ftest_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_TestEmployee_InfoEntry_DoNotUse_differential_5ftest_2eproto;
namespace DifferentialTest {
class CompanyDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Company> _instance;
} _Company_default_instance_;
class EducationInfoDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<EducationInfo> _instance;
} _EducationInfo_default_instance_;
class DependentInfoDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<DependentInfo> _instance;
} _DependentInfo_default_instance_;
class ExamScoreDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ExamScore> _instance;
} _ExamScore_default_instance_;
class TestEmployee_InfoEntry_DoNotUseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<TestEmployee_InfoEntry_DoNotUse> _instance;
} _TestEmployee_InfoEntry_DoNotUse_default_instance_;
class TestEmployeeDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<TestEmployee> _instance;
} _TestEmployee_default_instance_;
}  // namespace DifferentialTest
static void InitDefaultsscc_info_Company_differential_5ftest_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::DifferentialTest::_Company_default_instance_;
    new (ptr) ::DifferentialTest::Company();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::DifferentialTest::Company::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Company_differential_5ftest_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_Company_differential_5ftest_2eproto}, {}};

static void InitDefaultsscc_info_DependentInfo_differential_5ftest_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::DifferentialTest::_DependentInfo_default_instance_;
    new (ptr) ::DifferentialTest::DependentInfo();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::DifferentialTest::DependentInfo::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_DependentInfo_differential_5ftest_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_DependentInfo_differential_5ftest_2eproto}, {}};

static void InitDefaultsscc_info_EducationInfo_differential_5ftest_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::DifferentialTest::_EducationInfo_default_instance_;
    new (ptr) ::DifferentialTest::EducationInfo();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::DifferentialTest::EducationInfo::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_EducationInfo_differential_5ftest_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_EducationInfo_differential_5ftest_2eproto}, {}};

static void InitDefaultsscc_info_ExamScore_differential_5ftest_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::DifferentialTest::_ExamScore_default_instance_;
    new (ptr) ::DifferentialTest::ExamScore();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::DifferentialTest::ExamScore::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ExamScore_differential_5ftest_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_ExamScore_differential_5ftest_2eproto}, {}};

static void InitDefaultsscc_info_TestEmployee_differential_5ftest_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::DifferentialTest::_TestEmployee_default_instance_;
    new (ptr) ::DifferentialTest::TestEmployee();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::DifferentialTest::TestEmployee::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<5> scc_info_TestEmployee_differential_5ftest_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 5, 0, InitDefaultsscc_info_TestEmployee_differential_5ftest_2eproto}, {
      &scc_info_Company_differential_5ftest_2eproto.base,
      &scc_info_EducationInfo_differential_5ftest_2eproto.base,
      &scc_info_DependentInfo_differential_5ftest_2eproto.base,
      &scc_info_ExamScore_differential_5ftest_2eproto.base,
      &scc_info_TestEmployee_InfoEntry_DoNotUse_differential_5ftest_2eproto.base,}};

static void InitDefaultsscc_info_TestEmployee_InfoEntry_DoNotUse_differential_5ftest_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::DifferentialTest::_TestEmployee_InfoEntry_DoNotUse_default_instance_;
    new (ptr) ::DifferentialTest::TestEmployee_InfoEntry_DoNotUse();
  }
  ::DifferentialTest::TestEmployee_InfoEntry_DoNotUse::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_TestEmployee_InfoEntry_DoNotUse_differential_5ftest_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_TestEmployee_InfoEntry_DoNotUse_differential_5ftest_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_differential_5ftest_2eproto[6];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_differential_5ftest_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_differential_5ftest_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_differential_5ftest_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::DifferentialTest::Company, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::DifferentialTest::Company, name_),
  PROTOBUF_FIELD_OFFSET(::DifferentialTest::Company, occupation_),
  PROTOBUF_FIELD_OFFSET(::DifferentialTest::Company, address_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::DifferentialTest::EducationInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::DifferentialTest::EducationInfo, name_),
  PROTOBUF_FIELD_OFFSET(::DifferentialTest::EducationInfo, degree_),
  PROTOBUF_FIELD_OFFSET(::DifferentialTest::EducationInfo, major_),
  PROTOBUF_FIELD_OFFSET(::DifferentialTest::EducationInfo, address_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::DifferentialTest::DependentInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::DifferentialTest::DependentInfo, name_),
  PROTOBUF_FIELD_OFFSET(::DifferentialTest::DependentInfo, age_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::DifferentialTest::ExamScore, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::DifferentialTest::ExamScore, exam1_),
  PROTOBUF_FIELD_OFFSET(::DifferentialTest::ExamScore, score1_),
  PROTOBUF_FIELD_OFFSET(::DifferentialTest::ExamScore, exam2_),
  PROTOBUF_FIELD_OFFSET(::DifferentialTest::ExamScore, score2_),
  PROTOBUF_FIELD_OFFSET(::DifferentialTest::TestEmployee_InfoEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::DifferentialTest::TestEmployee_InfoEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::DifferentialTest::TestEmployee_InfoEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::DifferentialTest::TestEmployee_InfoEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::DifferentialTest::TestEmployee, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::DifferentialTest::TestEmployee, employ_id_),
  PROTOBUF_FIELD_OFFSET(::DifferentialTest::TestEmployee, fullname_),
  PROTOBUF_FIELD_OFFSET(::DifferentialTest::TestEmployee, age_),
  PROTOBUF_FIELD_OFFSET(::DifferentialTest::TestEmployee, employer_),
  PROTOBUF_FIELD_OFFSET(::DifferentialTest::TestEmployee, areas_),
  PROTOBUF_FIELD_OFFSET(::DifferentialTest::TestEmployee, education_),
  PROTOBUF_FIELD_OFFSET(::DifferentialTest::TestEmployee, dependents_),
  PROTOBUF_FIELD_OFFSET(::DifferentialTest::TestEmployee, floatpoint_),
  PROTOBUF_FIELD_OFFSET(::DifferentialTest::TestEmployee, exam_score_),
  PROTOBUF_FIELD_OFFSET(::DifferentialTest::TestEmployee, info_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::DifferentialTest::Company)},
  { 8, -1, sizeof(::DifferentialTest::EducationInfo)},
  { 17, -1, sizeof(::DifferentialTest::DependentInfo)},
  { 24, -1, sizeof(::DifferentialTest::ExamScore)},
  { 33, 40, sizeof(::DifferentialTest::TestEmployee_InfoEntry_DoNotUse)},
  { 42, -1, sizeof(::DifferentialTest::TestEmployee)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::DifferentialTest::_Company_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::DifferentialTest::_EducationInfo_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::DifferentialTest::_DependentInfo_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::DifferentialTest::_ExamScore_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::DifferentialTest::_TestEmployee_InfoEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::DifferentialTest::_TestEmployee_default_instance_),
};

const char descriptor_table_protodef_differential_5ftest_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\027differential_test.proto\022\020DifferentialT"
  "est\"<\n\007Company\022\014\n\004name\030\001 \001(\t\022\022\n\noccupati"
  "on\030\002 \001(\t\022\017\n\007address\030\003 \001(\t\"M\n\rEducationIn"
  "fo\022\014\n\004name\030\001 \001(\t\022\016\n\006degree\030\002 \001(\t\022\r\n\005majo"
  "r\030\003 \001(\t\022\017\n\007address\030\004 \001(\t\"*\n\rDependentInf"
  "o\022\014\n\004name\030\001 \003(\t\022\013\n\003age\030\002 \003(\005\"I\n\tExamScor"
  "e\022\r\n\005exam1\030\001 \001(\t\022\016\n\006score1\030\002 \001(\005\022\r\n\005exam"
  "2\030\003 \001(\t\022\016\n\006score2\030\004 \001(\002\"\217\003\n\014TestEmployee"
  "\022\021\n\temploy_id\030\001 \001(\005\022\020\n\010fullname\030\002 \001(\t\022\013\n"
  "\003age\030\003 \001(\005\022+\n\010employer\030\004 \001(\0132\031.Different"
  "ialTest.Company\022\r\n\005areas\030\005 \003(\t\0222\n\teducat"
  "ion\030\006 \003(\0132\037.DifferentialTest.EducationIn"
  "fo\0223\n\ndependents\030\007 \001(\0132\037.DifferentialTes"
  "t.DependentInfo\022\022\n\nfloatpoint\030\010 \001(\001\022/\n\ne"
  "xam_score\030\t \003(\0132\033.DifferentialTest.ExamS"
  "core\0226\n\004info\030\n \003(\0132(.DifferentialTest.Te"
  "stEmployee.InfoEntry\032+\n\tInfoEntry\022\013\n\003key"
  "\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_differential_5ftest_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_differential_5ftest_2eproto_sccs[6] = {
  &scc_info_Company_differential_5ftest_2eproto.base,
  &scc_info_DependentInfo_differential_5ftest_2eproto.base,
  &scc_info_EducationInfo_differential_5ftest_2eproto.base,
  &scc_info_ExamScore_differential_5ftest_2eproto.base,
  &scc_info_TestEmployee_differential_5ftest_2eproto.base,
  &scc_info_TestEmployee_InfoEntry_DoNotUse_differential_5ftest_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_differential_5ftest_2eproto_once;
static bool descriptor_table_differential_5ftest_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_differential_5ftest_2eproto = {
  &descriptor_table_differential_5ftest_2eproto_initialized, descriptor_table_protodef_differential_5ftest_2eproto, "differential_test.proto", 713,
  &descriptor_table_differential_5ftest_2eproto_once, descriptor_table_differential_5ftest_2eproto_sccs, descriptor_table_differential_5ftest_2eproto_deps, 6, 0,
  schemas, file_default_instances, TableStruct_differential_5ftest_2eproto::offsets,
  file_level_metadata_differential_5ftest_2eproto, 6, file_level_enum_descriptors_differential_5ftest_2eproto, file_level_service_descriptors_differential_5ftest_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_differential_5ftest_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_differential_5ftest_2eproto), true);
namespace DifferentialTest {

// ===================================================================

void Company::InitAsDefaultInstance() {
}
class Company::_Internal {
 public:
};

Company::Company()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:DifferentialTest.Company)
}
Company::Company(const Company& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_name().empty()) {
    name_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  occupation_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_occupation().empty()) {
    occupation_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.occupation_);
  }
  address_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_address().empty()) {
    address_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.address_);
  }
  // @@protoc_insertion_point(copy_constructor:DifferentialTest.Company)
}

void Company::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_Company_differential_5ftest_2eproto.base);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  occupation_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  address_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

Company::~Company() {
  // @@protoc_insertion_point(destructor:DifferentialTest.Company)
  SharedDtor();
}

void Company::SharedDtor() {
  name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  occupation_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  address_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void Company::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Company& Company::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Company_differential_5ftest_2eproto.base);
  return *internal_default_instance();
}


void Company::Clear() {
// @@protoc_insertion_point(message_clear_start:DifferentialTest.Company)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  occupation_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  address_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

const char* Company::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "DifferentialTest.Company.name"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string occupation = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_occupation();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "DifferentialTest.Company.occupation"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string address = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_address();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "DifferentialTest.Company.address"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Company::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:DifferentialTest.Company)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "DifferentialTest.Company.name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  // string occupation = 2;
  if (this->occupation().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_occupation().data(), static_cast<int>(this->_internal_occupation().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "DifferentialTest.Company.occupation");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_occupation(), target);
  }

  // string address = 3;
  if (this->address().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_address().data(), static_cast<int>(this->_internal_address().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "DifferentialTest.Company.address");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_address(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DifferentialTest.Company)
  return target;
}

size_t Company::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DifferentialTest.Company)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // string occupation = 2;
  if (this->occupation().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_occupation());
  }

  // string address = 3;
  if (this->address().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_address());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Company::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:DifferentialTest.Company)
  GOOGLE_DCHECK_NE(&from, this);
  const Company* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Company>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:DifferentialTest.Company)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:DifferentialTest.Company)
    MergeFrom(*source);
  }
}

void Company::MergeFrom(const Company& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:DifferentialTest.Company)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.occupation().size() > 0) {

    occupation_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.occupation_);
  }
  if (from.address().size() > 0) {

    address_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.address_);
  }
}

void Company::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:DifferentialTest.Company)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Company::CopyFrom(const Company& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DifferentialTest.Company)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Company::IsInitialized() const {
  return true;
}

void Company::InternalSwap(Company* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  name_.Swap(&other->name_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  occupation_.Swap(&other->occupation_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  address_.Swap(&other->address_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::PROTOBUF_NAMESPACE_ID::Metadata Company::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void EducationInfo::InitAsDefaultInstance() {
}
class EducationInfo::_Internal {
 public:
};

EducationInfo::EducationInfo()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:DifferentialTest.EducationInfo)
}
EducationInfo::EducationInfo(const EducationInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_name().empty()) {
    name_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  degree_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_degree().empty()) {
    degree_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.degree_);
  }
  major_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_major().empty()) {
    major_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.major_);
  }
  address_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_address().empty()) {
    address_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.address_);
  }
  // @@protoc_insertion_point(copy_constructor:DifferentialTest.EducationInfo)
}

void EducationInfo::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_EducationInfo_differential_5ftest_2eproto.base);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  degree_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  major_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  address_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

EducationInfo::~EducationInfo() {
  // @@protoc_insertion_point(destructor:DifferentialTest.EducationInfo)
  SharedDtor();
}

void EducationInfo::SharedDtor() {
  name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  degree_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  major_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  address_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void EducationInfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const EducationInfo& EducationInfo::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_EducationInfo_differential_5ftest_2eproto.base);
  return *internal_default_instance();
}


void EducationInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:DifferentialTest.EducationInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  degree_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  major_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  address_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

const char* EducationInfo::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "DifferentialTest.EducationInfo.name"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string degree = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_degree();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "DifferentialTest.EducationInfo.degree"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string major = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_major();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "DifferentialTest.EducationInfo.major"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string address = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          auto str = _internal_mutable_address();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "DifferentialTest.EducationInfo.address"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* EducationInfo::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:DifferentialTest.EducationInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "DifferentialTest.EducationInfo.name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  // string degree = 2;
  if (this->degree().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_degree().data(), static_cast<int>(this->_internal_degree().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "DifferentialTest.EducationInfo.degree");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_degree(), target);
  }

  // string major = 3;
  if (this->major().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_major().data(), static_cast<int>(this->_internal_major().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "DifferentialTest.EducationInfo.major");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_major(), target);
  }

  // string address = 4;
  if (this->address().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_address().data(), static_cast<int>(this->_internal_address().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "DifferentialTest.EducationInfo.address");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_address(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DifferentialTest.EducationInfo)
  return target;
}

size_t EducationInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DifferentialTest.EducationInfo)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // string degree = 2;
  if (this->degree().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_degree());
  }

  // string major = 3;
  if (this->major().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_major());
  }

  // string address = 4;
  if (this->address().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_address());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void EducationInfo::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:DifferentialTest.EducationInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const EducationInfo* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<EducationInfo>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:DifferentialTest.EducationInfo)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:DifferentialTest.EducationInfo)
    MergeFrom(*source);
  }
}

void EducationInfo::MergeFrom(const EducationInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:DifferentialTest.EducationInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.degree().size() > 0) {

    degree_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.degree_);
  }
  if (from.major().size() > 0) {

    major_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.major_);
  }
  if (from.address().size() > 0) {

    address_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.address_);
  }
}

void EducationInfo::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:DifferentialTest.EducationInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void EducationInfo::CopyFrom(const EducationInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DifferentialTest.EducationInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EducationInfo::IsInitialized() const {
  return true;
}

void EducationInfo::InternalSwap(EducationInfo* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  name_.Swap(&other->name_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  degree_.Swap(&other->degree_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  major_.Swap(&other->major_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  address_.Swap(&other->address_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::PROTOBUF_NAMESPACE_ID::Metadata EducationInfo::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void DependentInfo::InitAsDefaultInstance() {
}
class DependentInfo::_Internal {
 public:
};

DependentInfo::DependentInfo()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:DifferentialTest.DependentInfo)
}
DependentInfo::DependentInfo(const DependentInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      name_(from.name_),
      age_(from.age_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:DifferentialTest.DependentInfo)
}

void DependentInfo::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_DependentInfo_differential_5ftest_2eproto.base);
}

DependentInfo::~DependentInfo() {
  // @@protoc_insertion_point(destructor:DifferentialTest.DependentInfo)
  SharedDtor();
}

void DependentInfo::SharedDtor() {
}

void DependentInfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const DependentInfo& DependentInfo::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_DependentInfo_differential_5ftest_2eproto.base);
  return *internal_default_instance();
}


void DependentInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:DifferentialTest.DependentInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.Clear();
  age_.Clear();
  _internal_metadata_.Clear();
}

const char* DependentInfo::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_name();
            ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "DifferentialTest.DependentInfo.name"));
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else goto handle_unusual;
        continue;
      // repeated int32 age = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_age(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16) {
          _internal_add_age(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* DependentInfo::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:DifferentialTest.DependentInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string name = 1;
  for (int i = 0, n = this->_internal_name_size(); i < n; i++) {
    const auto& s = this->_internal_name(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "DifferentialTest.DependentInfo.name");
    target = stream->WriteString(1, s, target);
  }

  // repeated int32 age = 2;
  {
    int byte_size = _age_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          2, _internal_age(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DifferentialTest.DependentInfo)
  return target;
}

size_t DependentInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DifferentialTest.DependentInfo)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string name = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(name_.size());
  for (int i = 0, n = name_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      name_.Get(i));
  }

  // repeated int32 age = 2;
  {
    size_t data_size = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      Int32Size(this->age_);
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _age_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DependentInfo::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:DifferentialTest.DependentInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const DependentInfo* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<DependentInfo>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:DifferentialTest.DependentInfo)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:DifferentialTest.DependentInfo)
    MergeFrom(*source);
  }
}

void DependentInfo::MergeFrom(const DependentInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:DifferentialTest.DependentInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  name_.MergeFrom(from.name_);
  age_.MergeFrom(from.age_);
}

void DependentInfo::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:DifferentialTest.DependentInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DependentInfo::CopyFrom(const DependentInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DifferentialTest.DependentInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DependentInfo::IsInitialized() const {
  return true;
}

void DependentInfo::InternalSwap(DependentInfo* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  name_.InternalSwap(&other->name_);
  age_.InternalSwap(&other->age_);
}

::PROTOBUF_NAMESPACE_ID::Metadata DependentInfo::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void ExamScore::InitAsDefaultInstance() {
}
class ExamScore::_Internal {
 public:
};

ExamScore::ExamScore()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:DifferentialTest.ExamScore)
}
ExamScore::ExamScore(const ExamScore& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  exam1_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_exam1().empty()) {
    exam1_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.exam1_);
  }
  exam2_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_exam2().empty()) {
    exam2_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.exam2_);
  }
  ::memcpy(&score1_, &from.score1_,
    static_cast<size_t>(reinterpret_cast<char*>(&score2_) -
    reinterpret_cast<char*>(&score1_)) + sizeof(score2_));
  // @@protoc_insertion_point(copy_constructor:DifferentialTest.ExamScore)
}

void ExamScore::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ExamScore_differential_5ftest_2eproto.base);
  exam1_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  exam2_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&score1_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&score2_) -
      reinterpret_cast<char*>(&score1_)) + sizeof(score2_));
}

ExamScore::~ExamScore() {
  // @@protoc_insertion_point(destructor:DifferentialTest.ExamScore)
  SharedDtor();
}

void ExamScore::SharedDtor() {
  exam1_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  exam2_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void ExamScore::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ExamScore& ExamScore::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ExamScore_differential_5ftest_2eproto.base);
  return *internal_default_instance();
}


void ExamScore::Clear() {
// @@protoc_insertion_point(message_clear_start:DifferentialTest.ExamScore)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  exam1_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  exam2_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&score1_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&score2_) -
      reinterpret_cast<char*>(&score1_)) + sizeof(score2_));
  _internal_metadata_.Clear();
}

const char* ExamScore::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string exam1 = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_exam1();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "DifferentialTest.ExamScore.exam1"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 score1 = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          score1_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string exam2 = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_exam2();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "DifferentialTest.ExamScore.exam2"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // float score2 = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 37)) {
          score2_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ExamScore::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:DifferentialTest.ExamScore)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string exam1 = 1;
  if (this->exam1().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_exam1().data(), static_cast<int>(this->_internal_exam1().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "DifferentialTest.ExamScore.exam1");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_exam1(), target);
  }

  // int32 score1 = 2;
  if (this->score1() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_score1(), target);
  }

  // string exam2 = 3;
  if (this->exam2().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_exam2().data(), static_cast<int>(this->_internal_exam2().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "DifferentialTest.ExamScore.exam2");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_exam2(), target);
  }

  // float score2 = 4;
  if (!(this->score2() <= 0 && this->score2() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(4, this->_internal_score2(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DifferentialTest.ExamScore)
  return target;
}

size_t ExamScore::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DifferentialTest.ExamScore)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string exam1 = 1;
  if (this->exam1().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_exam1());
  }

  // string exam2 = 3;
  if (this->exam2().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_exam2());
  }

  // int32 score1 = 2;
  if (this->score1() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_score1());
  }

  // float score2 = 4;
  if (!(this->score2() <= 0 && this->score2() >= 0)) {
    total_size += 1 + 4;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ExamScore::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:DifferentialTest.ExamScore)
  GOOGLE_DCHECK_NE(&from, this);
  const ExamScore* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ExamScore>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:DifferentialTest.ExamScore)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:DifferentialTest.ExamScore)
    MergeFrom(*source);
  }
}

void ExamScore::MergeFrom(const ExamScore& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:DifferentialTest.ExamScore)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.exam1().size() > 0) {

    exam1_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.exam1_);
  }
  if (from.exam2().size() > 0) {

    exam2_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.exam2_);
  }
  if (from.score1() != 0) {
    _internal_set_score1(from._internal_score1());
  }
  if (!(from.score2() <= 0 && from.score2() >= 0)) {
    _internal_set_score2(from._internal_score2());
  }
}

void ExamScore::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:DifferentialTest.ExamScore)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ExamScore::CopyFrom(const ExamScore& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DifferentialTest.ExamScore)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ExamScore::IsInitialized() const {
  return true;
}

void ExamScore::InternalSwap(ExamScore* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  exam1_.Swap(&other->exam1_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  exam2_.Swap(&other->exam2_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(score1_, other->score1_);
  swap(score2_, other->score2_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ExamScore::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

TestEmployee_InfoEntry_DoNotUse::TestEmployee_InfoEntry_DoNotUse() {}
TestEmployee_InfoEntry_DoNotUse::TestEmployee_InfoEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void TestEmployee_InfoEntry_DoNotUse::MergeFrom(const TestEmployee_InfoEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata TestEmployee_InfoEntry_DoNotUse::GetMetadata() const {
  return GetMetadataStatic();
}
void TestEmployee_InfoEntry_DoNotUse::MergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::Message& other) {
  ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom(other);
}


// ===================================================================

void TestEmployee::InitAsDefaultInstance() {
  ::DifferentialTest::_TestEmployee_default_instance_._instance.get_mutable()->employer_ = const_cast< ::DifferentialTest::Company*>(
      ::DifferentialTest::Company::internal_default_instance());
  ::DifferentialTest::_TestEmployee_default_instance_._instance.get_mutable()->dependents_ = const_cast< ::DifferentialTest::DependentInfo*>(
      ::DifferentialTest::DependentInfo::internal_default_instance());
}
class TestEmployee::_Internal {
 public:
  static const ::DifferentialTest::Company& employer(const TestEmployee* msg);
  static const ::DifferentialTest::DependentInfo& dependents(const TestEmployee* msg);
};

const ::DifferentialTest::Company&
TestEmployee::_Internal::employer(const TestEmployee* msg) {
  return *msg->employer_;
}
const ::DifferentialTest::DependentInfo&
TestEmployee::_Internal::dependents(const TestEmployee* msg) {
  return *msg->dependents_;
}
TestEmployee::TestEmployee()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:DifferentialTest.TestEmployee)
}
TestEmployee::TestEmployee(const TestEmployee& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      areas_(from.areas_),
      education_(from.education_),
      exam_score_(from.exam_score_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  info_.MergeFrom(from.info_);
  fullname_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_fullname().empty()) {
    fullname_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.fullname_);
  }
  if (from._internal_has_employer()) {
    employer_ = new ::DifferentialTest::Company(*from.employer_);
  } else {
    employer_ = nullptr;
  }
  if (from._internal_has_dependents()) {
    dependents_ = new ::DifferentialTest::DependentInfo(*from.dependents_);
  } else {
    dependents_ = nullptr;
  }
  ::memcpy(&employ_id_, &from.employ_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&floatpoint_) -
    reinterpret_cast<char*>(&employ_id_)) + sizeof(floatpoint_));
  // @@protoc_insertion_point(copy_constructor:DifferentialTest.TestEmployee)
}

void TestEmployee::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_TestEmployee_differential_5ftest_2eproto.base);
  fullname_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&employer_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&floatpoint_) -
      reinterpret_cast<char*>(&employer_)) + sizeof(floatpoint_));
}

TestEmployee::~TestEmployee() {
  // @@protoc_insertion_point(destructor:DifferentialTest.TestEmployee)
  SharedDtor();
}

void TestEmployee::SharedDtor() {
  fullname_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete employer_;
  if (this != internal_default_instance()) delete dependents_;
}

void TestEmployee::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const TestEmployee& TestEmployee::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_TestEmployee_differential_5ftest_2eproto.base);
  return *internal_default_instance();
}


void TestEmployee::Clear() {
// @@protoc_insertion_point(message_clear_start:DifferentialTest.TestEmployee)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  areas_.Clear();
  education_.Clear();
  exam_score_.Clear();
  info_.Clear();
  fullname_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == nullptr && employer_ != nullptr) {
    delete employer_;
  }
  employer_ = nullptr;
  if (GetArenaNoVirtual() == nullptr && dependents_ != nullptr) {
    delete dependents_;
  }
  dependents_ = nullptr;
  ::memset(&employ_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&floatpoint_) -
      reinterpret_cast<char*>(&employ_id_)) + sizeof(floatpoint_));
  _internal_metadata_.Clear();
}

const char* TestEmployee::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 employ_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          employ_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string fullname = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_fullname();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "DifferentialTest.TestEmployee.fullname"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 age = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          age_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .DifferentialTest.Company employer = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_employer(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated string areas = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_areas();
            ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "DifferentialTest.TestEmployee.areas"));
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<42>(ptr));
        } else goto handle_unusual;
        continue;
      // repeated .DifferentialTest.EducationInfo education = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_education(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<50>(ptr));
        } else goto handle_unusual;
        continue;
      // .DifferentialTest.DependentInfo dependents = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 58)) {
          ptr = ctx->ParseMessage(_internal_mutable_dependents(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // double floatpoint = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 65)) {
          floatpoint_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // repeated .DifferentialTest.ExamScore exam_score = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 74)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_exam_score(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<74>(ptr));
        } else goto handle_unusual;
        continue;
      // map<string, string> info = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 82)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&info_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<82>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* TestEmployee::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:DifferentialTest.TestEmployee)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 employ_id = 1;
  if (this->employ_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_employ_id(), target);
  }

  // string fullname = 2;
  if (this->fullname().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_fullname().data(), static_cast<int>(this->_internal_fullname().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "DifferentialTest.TestEmployee.fullname");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_fullname(), target);
  }

  // int32 age = 3;
  if (this->age() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->_internal_age(), target);
  }

  // .DifferentialTest.Company employer = 4;
  if (this->has_employer()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        4, _Internal::employer(this), target, stream);
  }

  // repeated string areas = 5;
  for (int i = 0, n = this->_internal_areas_size(); i < n; i++) {
    const auto& s = this->_internal_areas(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "DifferentialTest.TestEmployee.areas");
    target = stream->WriteString(5, s, target);
  }

  // repeated .DifferentialTest.EducationInfo education = 6;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_education_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(6, this->_internal_education(i), target, stream);
  }

  // .DifferentialTest.DependentInfo dependents = 7;
  if (this->has_dependents()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        7, _Internal::dependents(this), target, stream);
  }

  // double floatpoint = 8;
  if (!(this->floatpoint() <= 0 && this->floatpoint() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(8, this->_internal_floatpoint(), target);
  }

  // repeated .DifferentialTest.ExamScore exam_score = 9;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_exam_score_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(9, this->_internal_exam_score(i), target, stream);
  }

  // map<string, string> info = 10;
  if (!this->_internal_info().empty()) {
    typedef ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::PROTOBUF_NAMESPACE_ID::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
          "DifferentialTest.TestEmployee.InfoEntry.key");
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
          p->second.data(), static_cast<int>(p->second.length()),
          ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
          "DifferentialTest.TestEmployee.InfoEntry.value");
      }
    };

    if (stream->IsSerializationDeterministic() &&
        this->_internal_info().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->_internal_info().size()]);
      typedef ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::size_type size_type;
      size_type n = 0;
      for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
          it = this->_internal_info().begin();
          it != this->_internal_info().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      for (size_type i = 0; i < n; i++) {
        target = TestEmployee_InfoEntry_DoNotUse::Funcs::InternalSerialize(10, items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second, target, stream);
        Utf8Check::Check(&(*items[static_cast<ptrdiff_t>(i)]));
      }
    } else {
      for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
          it = this->_internal_info().begin();
          it != this->_internal_info().end(); ++it) {
        target = TestEmployee_InfoEntry_DoNotUse::Funcs::InternalSerialize(10, it->first, it->second, target, stream);
        Utf8Check::Check(&(*it));
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DifferentialTest.TestEmployee)
  return target;
}

size_t TestEmployee::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DifferentialTest.TestEmployee)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string areas = 5;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(areas_.size());
  for (int i = 0, n = areas_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      areas_.Get(i));
  }

  // repeated .DifferentialTest.EducationInfo education = 6;
  total_size += 1UL * this->_internal_education_size();
  for (const auto& msg : this->education_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .DifferentialTest.ExamScore exam_score = 9;
  total_size += 1UL * this->_internal_exam_score_size();
  for (const auto& msg : this->exam_score_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // map<string, string> info = 10;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_info_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
      it = this->_internal_info().begin();
      it != this->_internal_info().end(); ++it) {
    total_size += TestEmployee_InfoEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  // string fullname = 2;
  if (this->fullname().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_fullname());
  }

  // .DifferentialTest.Company employer = 4;
  if (this->has_employer()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *employer_);
  }

  // .DifferentialTest.DependentInfo dependents = 7;
  if (this->has_dependents()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *dependents_);
  }

  // int32 employ_id = 1;
  if (this->employ_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_employ_id());
  }

  // int32 age = 3;
  if (this->age() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_age());
  }

  // double floatpoint = 8;
  if (!(this->floatpoint() <= 0 && this->floatpoint() >= 0)) {
    total_size += 1 + 8;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void TestEmployee::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:DifferentialTest.TestEmployee)
  GOOGLE_DCHECK_NE(&from, this);
  const TestEmployee* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<TestEmployee>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:DifferentialTest.TestEmployee)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:DifferentialTest.TestEmployee)
    MergeFrom(*source);
  }
}

void TestEmployee::MergeFrom(const TestEmployee& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:DifferentialTest.TestEmployee)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  areas_.MergeFrom(from.areas_);
  education_.MergeFrom(from.education_);
  exam_score_.MergeFrom(from.exam_score_);
  info_.MergeFrom(from.info_);
  if (from.fullname().size() > 0) {

    fullname_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.fullname_);
  }
  if (from.has_employer()) {
    _internal_mutable_employer()->::DifferentialTest::Company::MergeFrom(from._internal_employer());
  }
  if (from.has_dependents()) {
    _internal_mutable_dependents()->::DifferentialTest::DependentInfo::MergeFrom(from._internal_dependents());
  }
  if (from.employ_id() != 0) {
    _internal_set_employ_id(from._internal_employ_id());
  }
  if (from.age() != 0) {
    _internal_set_age(from._internal_age());
  }
  if (!(from.floatpoint() <= 0 && from.floatpoint() >= 0)) {
    _internal_set_floatpoint(from._internal_floatpoint());
  }
}

void TestEmployee::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:DifferentialTest.TestEmployee)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TestEmployee::CopyFrom(const TestEmployee& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DifferentialTest.TestEmployee)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TestEmployee::IsInitialized() const {
  return true;
}

void TestEmployee::InternalSwap(TestEmployee* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  areas_.InternalSwap(&other->areas_);
  education_.InternalSwap(&other->education_);
  exam_score_.InternalSwap(&other->exam_score_);
  info_.Swap(&other->info_);
  fullname_.Swap(&other->fullname_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(employer_, other->employer_);
  swap(dependents_, other->dependents_);
  swap(employ_id_, other->employ_id_);
  swap(age_, other->age_);
  swap(floatpoint_, other->floatpoint_);
}

::PROTOBUF_NAMESPACE_ID::Metadata TestEmployee::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace DifferentialTest
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::DifferentialTest::Company* Arena::CreateMaybeMessage< ::DifferentialTest::Company >(Arena* arena) {
  return Arena::CreateInternal< ::DifferentialTest::Company >(arena);
}
template<> PROTOBUF_NOINLINE ::DifferentialTest::EducationInfo* Arena::CreateMaybeMessage< ::DifferentialTest::EducationInfo >(Arena* arena) {
  return Arena::CreateInternal< ::DifferentialTest::EducationInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::DifferentialTest::DependentInfo* Arena::CreateMaybeMessage< ::DifferentialTest::DependentInfo >(Arena* arena) {
  return Arena::CreateInternal< ::DifferentialTest::DependentInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::DifferentialTest::ExamScore* Arena::CreateMaybeMessage< ::DifferentialTest::ExamScore >(Arena* arena) {
  return Arena::CreateInternal< ::DifferentialTest::ExamScore >(arena);
}
template<> PROTOBUF_NOINLINE ::DifferentialTest::TestEmployee_InfoEntry_DoNotUse* Arena::CreateMaybeMessage< ::DifferentialTest::TestEmployee_InfoEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateInternal< ::DifferentialTest::TestEmployee_InfoEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::DifferentialTest::TestEmployee* Arena::CreateMaybeMessage< ::DifferentialTest::TestEmployee >(Arena* arena) {
  return Arena::CreateInternal< ::DifferentialTest::TestEmployee >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
